import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import AuthClientLayout from "@/components/shared/AuthClientLayout";
import { Toaster } from "react-hot-toast";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "OOTG",
  description: "Generated by Kah Khing",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Toaster position="top-center" />
        <AuthClientLayout>{children}</AuthClientLayout>
      </body>
    </html>
  );
}
