import { Toaster } from "react-hot-toast";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Header from "@/components/cafeComponents/CafeHeader";
import Footer from "@/components/shared/Footer";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "OOTG",
  description: "Generated by Kah Khing",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <div className="flex flex-col justify-between h-screen">
          <Toaster position="top-center" />

          <Header />
          <div className="flex flex-col justify-center items-center pt-10">
            {children}
          </div>
          <Footer />
        </div>
      </body>
    </html>
  );
}
